### ISSUE TITLE
Fixing the Regex to Scrape All the Queries

### ISSUE THREAD

**Issue by sixthcodebrewer** [sixthcodebrewer/n1qlAutomation#1]
need an enchantment at regex that could look for 

> [source,n1ql]
for these two brackets and n1ql inside it.

which could help us scape all the queries from the [subquery](https://github.com/sixthcodebrewer/n1qlAutomation/blob/main/subqueries.adoc) page present in the repo.

**Comment by ajratnam** [comment]
@sixthcodebrewer  Is this what you wanted?
```py
>>> re.findall('\[.*?,n1ql\]',a)
['[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source,n1ql]', '[source#Q8,n1ql]', '[source#Q8A,n1ql]', '[source#Q9,n1ql]', '[source#Q9A,n1ql]']
```

**Comment by sixthcodebrewer** [comment]
@ajratnam hello,  well you got the half thing done, let me give you a little more background
I am looking to scrape 
```
SELECT count(*) FROM `travel-sample` .inventory.airport t
LET x = t.geo
WHERE (SELECT RAW y.alt FROM x y)[0] > 6000;
```

> from

```

[source,n1ql]
----
SELECT count(*) FROM `travel-sample` .inventory.airport t
LET x = t.geo
WHERE (SELECT RAW y.alt FROM x y)[0] > 6000;
----

```

I am looking for an updated regex which you get all necessary queries like the one above. 
Well the regex should the following things 
- Look for  [source,n1ql]
- then look for ---- four dash
- **scrape anything present in between it until it finds a semicolon** ;
- ending with four more dashes ---

**Comment by Alireza-Sampour** [comment]
Is [this](https://regex101.com/r/exseHd/1) is what are you looking for? if this is I can create a pull request for it.

**Comment by sixthcodebrewer** [comment]
> Is [this](https://regex101.com/r/Mb8U9S/1) is what are you looking for? if this is I can create a pull request for it.

Yes please go ahead, I would close the issue if someone submits the right pull request.

**Comment by Alireza-Sampour** [comment]
Can I do some refactoring to your code?

**Comment by sixthcodebrewer** [comment]
> Can I do some refactoring to your code?
please go ahead
Looking for the right output, Output needs to generate the files with scraped queries in them.

**Comment by sixthcodebrewer** [comment]
> > Is [this](https://regex101.com/r/Mb8U9S/1) is what are you looking for? if this is I can create a pull request for it.
> 
> Yes please go ahead, I would close the issue if someone submits the right pull request.

[File](https://github.com/sixthcodebrewer/n1qlAutomation/blob/main/subqueries.adoc)  
Make sure you use this file to run the queries, you have got what I am looking for, make sure the script also runs
you will need to look for [source#Q6B,n1ql], [source,n1ql] you need to generalize with both the cases #alpha-numeric which may be present or may not be present.

**Comment by Alireza-Sampour** [comment]
In this file, some lines look like don't wrote In SQL, [this](https://regex101.com/r/exseHd/2) is right? Or the lines like 34 must exclude?

**Comment by sixthcodebrewer** [comment]
> In this file, some lines look like don't wrote In SQL, [this](https://regex101.com/r/exseHd/2) is right? Or the lines like 34 must exclude?

Yes this is correct.

**Comment by Alireza-Sampour** [comment]
I created a pull request for it. let me know If there's is a problem with it.

**Comment by sixthcodebrewer** [comment]
> I created a pull request for it. let me know If there's is a problem with it.

Sure

**Comment by ajratnam** [comment]
Ah I'm late, guess this issue is fixed already 😄

**Comment by sixthcodebrewer** [comment]
@ajratnam would like to work more on the same project, well i have got something more to be done

**Comment by ajratnam** [comment]
Mhm, yes I can try.

**Comment by sixthcodebrewer** [comment]
> Mhm, yes I can try.

i will create more issues by the end of the day , have look at the same
